#! /bin/sh

# autostart applications
picom -b --experimental-backends  &
fcitx5 &
flameshot &
nm-applet &
dunst &

xrandr --output HDMI-1 --mode 1920x1080 --rate 120 --primary --output eDP-1 --off

feh --randomize --bg-fill ~/wallpaper/12.png
~/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor HDMI-1 -d 1 2 3 4 5 

bspc config border_width         0
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox state=floating
